import Head from 'next/head'
import styled from 'styled-components'

const Title = styled.h1`
font-size: 1.5em;
color: red;
`

export default function Home() {
  return (
    <>
      <Head>
        <title>メンバー 一覧 | Attendance-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title>メンバー一覧</Title>
        <p>メンバー一覧のページです。ここにコンポーネントを追加してください。</p>
      </main>
    </>
  )
}
