import Carousel from '@/components/Carousel'
import { Theme } from '@/types';
import Head from 'next/head'
import { useContext } from 'react';
import styled, { ThemeContext } from 'styled-components'

const Title = styled.h1`
font-size: 1.5em;
color: red;
`

export default function Home() {
  return (
    <>
      <Head>
        <title>HOME | Attendance-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title>HOME</Title>
        <Carousel />
        <p>HOMEのページです。ここにコンポーネントを追加してください。</p>
      </main>
    </>
  )
}
